name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
       
    steps:
    - uses: actions/checkout@v3

    - name: deploy api
      run: |
            cd ~/actions-runner/_work/StudyTube/StudyTube/backend
            npm i
            pm2 reload backend
