name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
       
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
            cd ~/actions-runner/_work/StudyTube/StudyTube/backend 
            curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
